name: PublishArtifact

on:
  pull_request_target:
    branches: [ master ]
    types: labeled

jobs:
  publish:
    name: publish artifact
    runs-on: windows-latest
    if: github.event.action == 'labeled' && github.event.label.name == 'rv'

    steps:
    #- name: Download artifact
    #  uses: actions/download-artifact@v1
    #  with:
    #    name: EasyEPLANner
    #    path: ./  
    
    #- name: Pack
    #  shell: powershell
    #  run: Compress-Archive -Path .\* -Update -DestinationPath EasyEPLANner.zip

    - name: Publish
    #run: > 
      #  curl 
      #  -H "Authorization: Bearer  ${{ secrets.GITHUB_TOKEN }}" 
      #  -X POST -d "{ 'body': 'TEST' }" 
      #  https://api.github.com/repos/KirillGutyrchik/EasyEPLANner/issues/${{ github.event.number }}/comments
      run: >
        curl -L 
        -X PATCH https://api.github.com/repos/KirillGutyrchik/EasyEPLANner/issues/${{ github.event.number }} 
        -H 'Accept: application/vnd.github+json' 
        -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
        -H 'X-GitHub-Api-Version: 2022-11-28' 
        -H 'content-type: application/json'
        --data '{
        "body": "TEST"
        }'